development:
  cloud_name: <%= ENV["CLOUD_NAME_DEV"] %>
  api_key: <%= ENV["API_KEY_DEV"] %>
  api_secret: <%= ENV["API_SECRET_DEV"] %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: <%= ENV["CLOUD_NAME_PROD"] %>
  api_key: <%= ENV["API_KEY_PROD"] %>
  api_secret: <%= ENV["API_SECRET_PROD"] %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: <%= ENV["CLOUD_NAME_TEST"] %>
  api_key: <%= ENV["API_KEY_TEST"] %>
  api_secret: <%= ENV["API_SECRET_TEST"] %>
  enhance_image_tag: true
  static_file_support: false
